plugins:
  - rubocop-factory_bot
  - rubocop-performance
  - rubocop-rails
  - rubocop-rspec

AllCops:
  Exclude:
    - "bin/**/*"
    - "db/schema.rb"
    - "log/**/*"
    - "node_modules/**/*"
    - "public/**/*"
    - "tmp/**/*"
    - "vendor/**/*"
  NewCops: enable
  SuggestExtensions: false

# Bundler

Bundler/GemComment:
  OnlyFor: [version_specifiers]

Bundler/OrderedGems:
  TreatCommentsAsGroupSeparators: false

# Layout

Layout/CaseIndentation:
  EnforcedStyle: end

Layout/ClassStructure:
  Enabled: true

Layout/EndAlignment:
  EnforcedStyleAlignWith: variable

Layout/FirstArgumentIndentation:
  EnforcedStyle: consistent

Layout/FirstArrayElementIndentation:
  EnforcedStyle: consistent

Layout/FirstHashElementIndentation:
  EnforcedStyle: consistent

Layout/HeredocArgumentClosingParenthesis:
  Enabled: true

Layout/MultilineMethodCallIndentation:
  EnforcedStyle: indented

Layout/LineLength:
  Enabled: false

# Lint

Lint/AmbiguousBlockAssociation:
  Exclude:
    - "spec/**/*"

Lint/AssignmentInCondition:
  AllowSafeAssignment: false

# Metrics

Metrics:
  Enabled: false

# Style

Style/BlockDelimiters:
  EnforcedStyle: semantic
  Exclude:
    # `name { 'foo' }` is preferred over `name do 'foo' end` for factory_bot
    - 'spec/factories/**/*'

Style/DateTime:
  Enabled: true

Style/Documentation:
  Enabled: false

Style/EmptyMethod:
  EnforcedStyle: expanded

Style/FloatDivision:
  EnforcedStyle: fdiv

Style/HashSyntax:
  EnforcedShorthandSyntax: consistent

Style/IfUnlessModifier:
  Enabled: false

Style/InvertibleUnlessCondition:
  Enabled: true

Style/Lambda:
  EnforcedStyle: literal

Style/MethodCalledOnDoEndBlock:
  Enabled: true

Style/MultilineBlockChain:
  Enabled: false

Style/MultilineMethodSignature:
  Enabled: true

Style/PercentLiteralDelimiters:
  PreferredDelimiters:
    "%i": "()"
    "%I": "()"
    "%w": "()"
    "%W": "()"

Style/ReturnNil:
  Enabled: true

Style/StringMethods:
  Enabled: true

Style/SymbolProc:
  AllowedMethods:
    # `create_table :users do |t| t.timestamps end` is preferred over `create_table :users, &timestamps`
    - create_table

Style/TrailingCommaInBlockArgs:
  Enabled: true

# Performance

Performance/IoReadlines:
  Enabled: true

Performance/RedundantMerge:
  MaxKeyValuePairs: 1

# Rails

Rails/DefaultScope:
  Enabled: true

Rails/HasManyOrHasOneDependent:
  Enabled: false

Rails/I18nLocaleTexts:
  Enabled: false

Rails/RakeEnvironment:
  Enabled: false

Rails/ReversibleMigrationMethodDefinition:
  Enabled: true

Rails/SaveBang:
  Enabled: true

# RSpec

RSpec/ExampleLength:
  Enabled: false

RSpec/ExpectChange:
  Enabled: false

RSpec/MultipleExpectations:
  Enabled: false
